### ISSUE TITLE
Upload to PyPi

### ISSUE THREAD

**Issue by part1zano** [awahlig/python-pcre#6]
Hi, we're submitting a FreeBSD Port for this project, and we'd like to know exactly what its name is. Is it python-pcre or just pcre? So please upload it to PyPi so we know exactly.

**Comment by koobs** [comment]
Suggest: pcre (as its untaken) even if the repository name (python-pcre) stays the same :)

**Comment by xmj** [comment]
(related, packaging on FreeBSD:) Could you please add version number tags?

**Comment by koobs** [comment]
@xmj Create a new issue :)

**Comment by part1zano** [comment]
Do you have any updates on this issue? It has already been a while.

**Comment by awahlig** [comment]
The project is now on PyPi:
https://pypi.python.org/pypi/python-pcre

Sorry for the delay.
The name of the project is python-pcre -- I want to keep that consistent.

**Comment by xmj** [comment]
Thanks!

**Comment by part1zano** [comment]
Thank you!
